### ISSUE TITLE
Count on empty list displays incorrect result in velocity renderer

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/elda#153]
When accessing a list endpoint, with a parameter "_count=yes", the velocity renderer will display a count of the total number of results, e.g.

  Showing 1 to 10 of 100

When the list is empty, i.e. the count is 0, the renderer displays

  Showing 1 to 0 of 0

**Comment by ijdickinson** [comment]
There's a fix in the `issue-153` branch now. Unfortunately, it will require a new release as the change is in the Java code, not the Velocity macros.

**Comment by ijdickinson** [comment]
@bwmcbride I think this branch has been merged now so the fix should be applied. Can you confirm, and close if appropriate please?

**Comment by bwmcbride** [comment]
Tried to verify on a recent deployment but Elda is giving me a 500 error when I add an _count=yes to the request.  Logs show it is throwing an exception:

2017-07-03 08:59:33,171 ERROR [http-apr-8080-exec-8] (RouterRestlet.java:435) - Exception: this endpoint does not allow _count to be altered.
07:59:33		Jul 03, 2017 8:59:33 AM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
07:59:33		SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
07:59:33		com.epimorphics.lda.exceptions.GeneralException
07:59:33			at com.epimorphics.lda.restlets.RouterRestlet.runEndpoint(RouterRestlet.java:437)
07:59:33			at com.epimorphics.lda.restlets.RouterRestlet.requestHandler(RouterRestlet.java:255)
07:59:33			at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
07:59:33			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
07:59:33			at java.lang.reflect.Method.invoke(Method.java:498)
07:59:33			at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)

If I am reading that right - this should be a 400 error not a 500 error.

**Comment by ijdickinson** [comment]
@ehedgehog I think that:

     Exception: this endpoint does not allow _count to be altered

returning error 500 instead of 403 forbidden is not a Velocity issue. Re-assigning to you.
