### ISSUE TITLE
Incorrect handling of URI with escaped space characters (%20)

### ISSUE THREAD

**Issue by skwlilac** [epimorphics/elda#156]
elda-common is configured as a filter rather than a servlet. Request that elda can't handle (normally those that 404 either because there are no matching api:templates or because there is no corresponding item in the triple store) are passed on down the filter chain and ultimately handled by a default servlet that typically serves up a file.

Unfortuately when presented with a URI that contains escaped spaces (and/or escapes of other characters that are not allowed in a URI) ELDA can formulate SPARQL queries that it rejects as invalid because of the now unescaped characters. This causes elda to throw a 500 internal error response, and the request never gets the opportunity to pass on down the filter chain and be served up by the default servlet.

For example if the request:

```
http://localhost/landregistry/lda-assets/images/grey/16x16/Arrow3%20Up.png
```

reaches a 'catchall' endpoint within ELDA, it formulate the SPARQL query:

```
CONSTRUCT {
} WHERE {
  { VALUES ?item { 
  <http://landregistry.data.gov.uk/lda-assets/images/grey/16x16/Arrow3 Up.png>
} }
```
which generates a query parse exception due to the 'space' character arsing from the decoded %20 in the original request URI. Stack trace below:

```
2015-03-09 16:03:35.410 ERROR [http-bio-80-exec-3] (ELog.java:51) - []: general failure: com.hp.hpl.jena.query.QueryParseException: Encountered " "<" "< "" at line 4, column 3.
Was expecting one of:
    <IRIref> ...
    <PNAME_NS> ...
    <PNAME_LN> ...
    "undef" ...
    "true" ...
    "false" ...
    <INTEGER> ...
    <DECIMAL> ...
    <DOUBLE> ...
    <INTEGER_POSITIVE> ...
    <DECIMAL_POSITIVE> ...
    <DOUBLE_POSITIVE> ...
    <INTEGER_NEGATIVE> ...
    <DECIMAL_NEGATIVE> ...
    <DOUBLE_NEGATIVE> ...
    <STRING_LITERAL1> ...
    <STRING_LITERAL2> ...
    <STRING_LITERAL_LONG1> ...
    <STRING_LITERAL_LONG2> ...
    "}" ...
    
com.hp.hpl.jena.query.QueryParseException: Encountered " "<" "< "" at line 4, column 3.
Was expecting one of:
    <IRIref> ...
    <PNAME_NS> ...
    <PNAME_LN> ...
    "undef" ...
    "true" ...
    "false" ...
    <INTEGER> ...
    <DECIMAL> ...
    <DOUBLE> ...
    <INTEGER_POSITIVE> ...
    <DECIMAL_POSITIVE> ...
    <DOUBLE_POSITIVE> ...
    <INTEGER_NEGATIVE> ...
    <DECIMAL_NEGATIVE> ...
    <DOUBLE_NEGATIVE> ...
    <STRING_LITERAL1> ...
    <STRING_LITERAL2> ...
    <STRING_LITERAL_LONG1> ...
    <STRING_LITERAL_LONG2> ...
    "}" ...
    
	at com.hp.hpl.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:102)
	at com.hp.hpl.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:53)
	at com.hp.hpl.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:37)
	at com.hp.hpl.jena.query.QueryFactory.parse(QueryFactory.java:156)
	at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:79)
	at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:52)
	at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:40)
	at com.epimorphics.lda.core.View.fetchByGivenPropertyChains(View.java:334)
	at com.epimorphics.lda.core.View.fetchDescriptions(View.java:281)
	at com.epimorphics.lda.core.View.fetchDescriptionsFor(View.java:422)
	at com.epimorphics.lda.query.APIQuery.fetchDescriptionOfAllResources(APIQuery.java:947)
	at com.epimorphics.lda.query.APIQuery.runQueryWithSource(APIQuery.java:900)
	at com.epimorphics.lda.query.APIQuery.runQuery(APIQuery.java:881)
	at com.epimorphics.lda.core.APIEndpointImpl.freshResponse(APIEndpointImpl.java:132)
	at com.epimorphics.lda.core.APIEndpointImpl.call_revised(APIEndpointImpl.java:118)
	at com.epimorphics.lda.core.APIEndpointImpl.call(APIEndpointImpl.java:92)
	at com.epimorphics.lda.core.APIEndpointUtil.call(APIEndpointUtil.java:53)
	at com.epimorphics.lda.restlets.RouterRestlet.runEndpoint(RouterRestlet.java:398)
	at com.epimorphics.lda.restlets.RouterRestlet.requestHandler(RouterRestlet.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:927)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:875)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:829)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```

**Comment by ehedgehog** [comment]
RouterRestlet now requests that the @PathParam be @Encoded and so
strings van be used as URIs in generated SPARQL,
eg esp spaces are represented by %20.
