### ISSUE TITLE
ConcurrentModificationException when sorting templates 

### ISSUE THREAD

**Issue by dratc** [epimorphics/elda#170]
We are running the standalone version from the master branch with Java 8, and occasionally see the following exception (truncated):

`Sep 13, 2016 12:19:07 AM com.sun.jersey.spi.container.ContainerResponse mapMappableContainerException
SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.util.ConcurrentModificationException
    at java.util.ArrayList.sort(ArrayList.java:1456)
    at java.util.Collections.sort(Collections.java:175)
    at com.epimorphics.lda.routing.MatchSearcher.sortTemplates(MatchSearcher.java:77)
    at com.epimorphics.lda.routing.MatchSearcher.lookup(MatchSearcher.java:69)
    at com.epimorphics.lda.routing.DefaultRouter.getMatch(DefaultRouter.java:48)
    at com.epimorphics.lda.restlets.RouterRestlet.getMatch(RouterRestlet.java:195)
    at com.epimorphics.lda.restlets.RouterRestlet.requestHandler(RouterRestlet.java:232)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

[This post](http://onelineatatime.io/collections-sort-the-java8u20-modification/) might describe what is happening -- the implementation of Collections.sort appears to have changed since Java8u20. 

We resolved this by providing synchronisation around access to the template list in com.epimorphics.lda.routing.MatchSearcher.

**Comment by ehedgehog** [comment]
Synchronisation applied to template-using code in MatchSearcher.
Suspect there may be a higher-level problem with reloading
specifications - more work required.
