### ISSUE TITLE
[JSON-LD Renderer] Wrapped Exception

### ISSUE THREAD

**Issue by pasqLisena** [epimorphics/elda#180]
Hello, I have a blocking error while using the JSON-LD render. What it can be? Thank you

This is my configuration:
```turtle
@prefix api: <http://purl.org/linked-data/api/vocab#> .
@prefix apivc: <http://purl.org/linked-data/api/vocab#> .
@prefix crm: <http://www.cidoc-crm.org/cidoc-crm/> .
@prefix doremus: <http://data.doremus.org/elda/vocabulary/> .
@prefix ecrm: <http://erlangen-crm.org/current/> .
@prefix efrbroo: <http://erlangen-crm.org/efrbroo/> .
@prefix elda: <http://www.epimorphics.com/vocabularies/lda#> .
@prefix mus: <http://data.doremus.org/ontology#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix spec: <http://education.data.gov.uk/api-config#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix schema: 			<http://schema.org/> .

doremus:Expressions a apivc:API ;
    rdfs:label "DOREMUS Open Data" ;
    apivc:base "/" ;
    apivc:defaultFormatter doremus:HtmlFormatter ;
    apivc:defaultViewer doremus:viewExpressionsList ;
    apivc:endpoint doremus:expressions, doremus:expression ;
    apivc:formatter doremus:HtmlFormatter, doremus:JsonLDFormatter ;
    apivc:sparqlEndpoint <http://data.doremus.org/sparql> ;
    apivc:variable [ apivc:name "_exceptionIfEmpty" ;
            apivc:value "no" ],
        [ apivc:name "_resourceRoot" ;
            apivc:value "http://localhost:8080/elda-assets/" ] ;
    apivc:viewer doremus:viewExpressionsList , doremus:viewExpression ;
    elda:enableCounting "false" .
    
doremus:HtmlFormatter a apivc:XsltFormatter ;
    apivc:mimeType "text/html; charset=utf-8" ;
    apivc:name "html" ;
    apivc:stylesheet "http://localhost:8080/elda-assets/xslt/result.xsl" .

doremus:JsonLDFormatter a api:JsonFormatter
        ; api:name "json-ld"
        ; elda:checkJSONLDRoundTrip false
        ; elda:allLiteralsStructured false
        ; elda:className "com.epimorphics.lda.renderers.JSONLDRendererFactory"
    #
    # use /json if client doesn't render json-ld as json, otherwise
    # use /json+ld. Firefox doesn't understand +ld so we'll force to /json
    # for the moment.
    # 
        ; api:mimeType "application/json"
        # ; api:mimeType "application/json+ld"
.

doremus:expressions a apivc:ListEndpoint ;
    rdfs:label "Expressions" ;
    apivc:selector [ apivc:orderBy "STR(?s1)" ;
            apivc:where """      
    GRAPH ?g { ?item a efrbroo:F22_Self-Contained_Expression .}
    VALUES ?g {<http://data.doremus.org/bnf> <http://data.doremus.org/philharmonie> <http://data.doremus.org/vocabularies> }
      BIND(1 as ?s1)      
    """] ;
    apivc:uriTemplate "/expression" .
    
doremus:expression a apivc:ItemEndpoint ;
    rdfs:label "Expression" ;
    api:variable [api:name "uriExp"; api:value <http://data.doremus.org/expression/{uuid}>]	;				
    apivc:selector [
            apivc:where """      
    GRAPH ?g { ?item a efrbroo:F22_Self-Contained_Expression .}
    VALUES ?g {<http://data.doremus.org/bnf> <http://data.doremus.org/philharmonie> <http://data.doremus.org/vocabularies> }
    FILTER (?item = IRI(?uriExp))	.					
    """] ;
    api:defaultViewer doremus:viewExpression ;
    apivc:uriTemplate "/expression/{uuid}" .

doremus:viewExpressionsList a apivc:Viewer ;
    apivc:name "list" ;
    apivc:properties "U11_has_key.prefLabel",
        "U12_has_genre.prefLabel",
        "label" .
        
doremus:viewExpression a apivc:Viewer ;
    apivc:name "list" ;
    apivc:properties "U11_has_key.prefLabel",
        "U12_has_genre.prefLabel",
        "label" .


#*******************************************************************
# 					Vocabulario
#*******************************************************************	


mus:U11_has_key 	api:label	"U11_has_key"
							; api:multiValued 	true 
							; rdfs:range 		rdfs:Class 
							.
mus:U12_has_genre 	api:label	"U12_has_genre"
							; api:multiValued 	true 
							; rdfs:range 		rdfs:Class 
							.
              
skos:prefLabel							api:label	"prefLabel".
```

This is what I have in console. 
```
2017-04-03 23:27:45,470 ERROR [http-bio-8080-exec-8] (RouterRestlet.java:593) - [5]: Error while sending response: 'com.hp.hpl.jena.shared.WrappedException: com.epimorphics.jsonrdf.EncodingException: cannot finish with '}
' inside '['.'
com.hp.hpl.jena.shared.WrappedException: com.epimorphics.jsonrdf.EncodingException: cannot finish with '}
' inside '['.
	at com.epimorphics.lda.renderers.JSONLDRenderer$1.writeAll(JSONLDRenderer.java:95)
	at com.epimorphics.lda.renderers.BytesOutTimed.writeAll(BytesOutTimed.java:34)
	at com.epimorphics.lda.restlets.RouterRestlet$2.write(RouterRestlet.java:589)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:71)
	at com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:57)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1510)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:927)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:875)
	at com.sun.jersey.spi.container.servlet.ServletContainer.doFilter(ServletContainer.java:829)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.epimorphics.lda.support.LogRequestFilter.doFilter(LogRequestFilter.java:74)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.epimorphics.jsonrdf.EncodingException: cannot finish with '}
' inside '['.
	at com.epimorphics.jsonrdf.JSONWriterWrapper.endObject(JSONWriterWrapper.java:67)
	at com.epimorphics.lda.renderers.JSONLDComposer.value(JSONLDComposer.java:184)
	at com.epimorphics.lda.renderers.JSONLDComposer.composeProperties(JSONLDComposer.java:141)
	at com.epimorphics.lda.renderers.JSONLDComposer.renderResource(JSONLDComposer.java:117)
	at com.epimorphics.lda.renderers.JSONLDComposer.value(JSONLDComposer.java:161)
	at com.epimorphics.lda.renderers.JSONLDComposer.composeProperties(JSONLDComposer.java:141)
	at com.epimorphics.lda.renderers.JSONLDComposer.renderResource(JSONLDComposer.java:117)
	at com.epimorphics.lda.renderers.JSONLDComposer.value(JSONLDComposer.java:161)
	at com.epimorphics.lda.renderers.JSONLDComposer.composeProperties(JSONLDComposer.java:138)
	at com.epimorphics.lda.renderers.JSONLDComposer.renderResource(JSONLDComposer.java:117)
	at com.epimorphics.lda.renderers.JSONLDComposer.renderItems(JSONLDComposer.java:82)
	at com.epimorphics.lda.renderers.JSONLDRenderer$1.writeAll(JSONLDRenderer.java:84)
	... 33 more
Caused by: org.apache.jena.atlas.json.JsonException: cannot finish with '}
' inside '['.
	at com.epimorphics.jsonrdf.extras.JSStreamingWriter.finishCompound(JSStreamingWriter.java:194)
	at com.epimorphics.jsonrdf.extras.JSStreamingWriter.finishObject(JSStreamingWriter.java:59)
	at com.epimorphics.jsonrdf.JSONWriterWrapper.endObject(JSONWriterWrapper.java:65)
	... 44 more
```

**Comment by ehedgehog** [comment]
Bug in JSONLDCOmposer, in the case of a literal with language the nested
object didn't have its opening '{'.

Will be fixed in 1.3.25. Fixed in current snapshot.
