### ISSUE TITLE
Wrong way for reading log4.properties file


### ISSUE THREAD

**Issue by ehedgehog** [epimorphics/elda#20]
<pre>Using ELDA (1.2.6-SNAPSHOT) on my webapp, I&#39;m getting the following error launching it:

16:58:12,066 com.epimorphics.lda.routing.Loader:88 INFO : Starting Elda 1.2.6-SNAPSHOT
log4j:ERROR Could not read configuration file [/home/sergio/projects/foo/src/main/webapp/log4j.properties].
java.io.FileNotFoundException: /home/sergio/projects/foo/src/main/webapp/log4j.properties (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:120)
    at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:79)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:316)
    at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:342)
    at com.epimorphics.lda.routing.Loader.configureLog4J(Loader.java:148)
    at com.epimorphics.lda.routing.Loader.init(Loader.java:89)
    at javax.servlet.GenericServlet.init(GenericServlet.java:241)

The library should not look up at such path. IMO it should do it from the classpath, adding something like this to com.epimorphics.lda.routing.Loader.configureLog4J() at line 149:

PropertyConfigurator.configure(Thread.currentThread().getContextClassLoader().getResource(file).getFile());

</pre>

**Comment by simonoakesepimorphics** [comment]
Closing this as version 3.0.0 replaced log4j with logback.
